# Local Development Profile

# Disable RabbitMQ auto-configuration and health check since it's not required locally
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
management.health.rabbit.enabled=false

# Disable MinIO to prevent startup errors and Connection refused exceptions
minio.enabled=false
